### ISSUE TITLE
Localisation of config screen

### ISSUE THREAD

**Issue by bartbutenaers** [bartbutenaers/node-red-dashboard-2-ui-video#7]
Currently the labels on the config screen (i.e. html file) are hardcoded in English.  It would be nice to get those labels from the [ui-video.json](https://github.com/bartbutenaers/node-red-dashboard-2-ui-video/blob/main/nodes/locales/en-US/ui-video.json) file, to allow users to translate the config screen in their own language.

Not sure yet how to do this in a custom node, so I have asked it [here](https://github.com/FlowFuse/node-red-dashboard-2-ui-example/issues/18).

**Comment by joepavitt** [comment]
I've addressed this [here](https://github.com/FlowFuse/node-red-dashboard-2-ui-example/issues/18)

**Comment by bartbutenaers** [comment]
Thanks @joepavitt !
Localisation of the config screen completed
